import { join } from 'node:path'

import tailwindcss from '@tailwindcss/vite'
import viteReact from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import tsconfigPaths from 'vite-tsconfig-paths'

// The gallery, which is the app's screens and none of the app's wiring.

// Deliberately not the app's config with a flag on it. That one carries TanStack Start, which means a router, a root route, and `ClerkProvider` inside it -- the whole of what makes a screen need a sign-in before it will draw. Keeping them apart is what lets a signed-out machine render a signed-in screen.

// No `envDir` and no `envPrefix` either: nothing here reads a deployment, and a gallery that could would be one config change away from pointing at the real one.
export default defineConfig({
  root: import.meta.dirname,
  // Named, because this root has no `index.html`: the app's own entry is generated by TanStack Start and never sits on disk beside this one.
  build: {
    outDir: 'dist-gallery',
    emptyOutDir: true,
    rollupOptions: { input: join(import.meta.dirname, 'gallery.html') },
  },
  plugins: [
    tsconfigPaths({ projects: ['../tsconfig.app.json'] }),
    tailwindcss(),
    viteReact({ babel: { plugins: ['babel-plugin-react-compiler'] } }),
  ],
})
