/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as OwedRouteImport } from './routes/owed'
import { Route as MoreRouteImport } from './routes/more'
import { Route as DaybookRouteImport } from './routes/daybook'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoreIndexRouteImport } from './routes/more.index'
import { Route as SitesNewRouteImport } from './routes/sites.new'
import { Route as ReceiptsNewRouteImport } from './routes/receipts.new'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as MoreWhoCanSignInRouteImport } from './routes/more.who-can-sign-in'
import { Route as MoreWhichAccountRouteImport } from './routes/more.which-account'
import { Route as MoreWhatForRouteImport } from './routes/more.what-for'
import { Route as MoreHowItLooksRouteImport } from './routes/more.how-it-looks'
import { Route as SitesSiteIdIndexRouteImport } from './routes/sites.$siteId.index'
import { Route as SitesSiteIdSharesRouteImport } from './routes/sites.$siteId.shares'
import { Route as SitesSiteIdReceiptsRouteImport } from './routes/sites.$siteId.receipts'
import { Route as SitesSiteIdDaybookRouteImport } from './routes/sites.$siteId.daybook'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const OwedRoute = OwedRouteImport.update({
  id: '/owed',
  path: '/owed',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const DaybookRoute = DaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreIndexRoute = MoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoreRoute,
} as any)
const SitesNewRoute = SitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsNewRoute = ReceiptsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReceiptsRoute,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PeopleRoute,
} as any)
const MoreWhoCanSignInRoute = MoreWhoCanSignInRouteImport.update({
  id: '/who-can-sign-in',
  path: '/who-can-sign-in',
  getParentRoute: () => MoreRoute,
} as any)
const MoreWhichAccountRoute = MoreWhichAccountRouteImport.update({
  id: '/which-account',
  path: '/which-account',
  getParentRoute: () => MoreRoute,
} as any)
const MoreWhatForRoute = MoreWhatForRouteImport.update({
  id: '/what-for',
  path: '/what-for',
  getParentRoute: () => MoreRoute,
} as any)
const MoreHowItLooksRoute = MoreHowItLooksRouteImport.update({
  id: '/how-it-looks',
  path: '/how-it-looks',
  getParentRoute: () => MoreRoute,
} as any)
const SitesSiteIdIndexRoute = SitesSiteIdIndexRouteImport.update({
  id: '/sites/$siteId/',
  path: '/sites/$siteId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdSharesRoute = SitesSiteIdSharesRouteImport.update({
  id: '/sites/$siteId/shares',
  path: '/sites/$siteId/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdReceiptsRoute = SitesSiteIdReceiptsRouteImport.update({
  id: '/sites/$siteId/receipts',
  path: '/sites/$siteId/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdDaybookRoute = SitesSiteIdDaybookRouteImport.update({
  id: '/sites/$siteId/daybook',
  path: '/sites/$siteId/daybook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/daybook': typeof DaybookRoute
  '/more': typeof MoreRouteWithChildren
  '/owed': typeof OwedRoute
  '/people': typeof PeopleRouteWithChildren
  '/receipts': typeof ReceiptsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/more/how-it-looks': typeof MoreHowItLooksRoute
  '/more/what-for': typeof MoreWhatForRoute
  '/more/which-account': typeof MoreWhichAccountRoute
  '/more/who-can-sign-in': typeof MoreWhoCanSignInRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/sites/new': typeof SitesNewRoute
  '/more/': typeof MoreIndexRoute
  '/sites/$siteId/daybook': typeof SitesSiteIdDaybookRoute
  '/sites/$siteId/receipts': typeof SitesSiteIdReceiptsRoute
  '/sites/$siteId/shares': typeof SitesSiteIdSharesRoute
  '/sites/$siteId/': typeof SitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/daybook': typeof DaybookRoute
  '/owed': typeof OwedRoute
  '/people': typeof PeopleRouteWithChildren
  '/receipts': typeof ReceiptsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/more/how-it-looks': typeof MoreHowItLooksRoute
  '/more/what-for': typeof MoreWhatForRoute
  '/more/which-account': typeof MoreWhichAccountRoute
  '/more/who-can-sign-in': typeof MoreWhoCanSignInRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/sites/new': typeof SitesNewRoute
  '/more': typeof MoreIndexRoute
  '/sites/$siteId/daybook': typeof SitesSiteIdDaybookRoute
  '/sites/$siteId/receipts': typeof SitesSiteIdReceiptsRoute
  '/sites/$siteId/shares': typeof SitesSiteIdSharesRoute
  '/sites/$siteId': typeof SitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/daybook': typeof DaybookRoute
  '/more': typeof MoreRouteWithChildren
  '/owed': typeof OwedRoute
  '/people': typeof PeopleRouteWithChildren
  '/receipts': typeof ReceiptsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/more/how-it-looks': typeof MoreHowItLooksRoute
  '/more/what-for': typeof MoreWhatForRoute
  '/more/which-account': typeof MoreWhichAccountRoute
  '/more/who-can-sign-in': typeof MoreWhoCanSignInRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/sites/new': typeof SitesNewRoute
  '/more/': typeof MoreIndexRoute
  '/sites/$siteId/daybook': typeof SitesSiteIdDaybookRoute
  '/sites/$siteId/receipts': typeof SitesSiteIdReceiptsRoute
  '/sites/$siteId/shares': typeof SitesSiteIdSharesRoute
  '/sites/$siteId/': typeof SitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/daybook'
    | '/more'
    | '/owed'
    | '/people'
    | '/receipts'
    | '/reports'
    | '/more/how-it-looks'
    | '/more/what-for'
    | '/more/which-account'
    | '/more/who-can-sign-in'
    | '/people/$personId'
    | '/receipts/new'
    | '/sites/new'
    | '/more/'
    | '/sites/$siteId/daybook'
    | '/sites/$siteId/receipts'
    | '/sites/$siteId/shares'
    | '/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/daybook'
    | '/owed'
    | '/people'
    | '/receipts'
    | '/reports'
    | '/more/how-it-looks'
    | '/more/what-for'
    | '/more/which-account'
    | '/more/who-can-sign-in'
    | '/people/$personId'
    | '/receipts/new'
    | '/sites/new'
    | '/more'
    | '/sites/$siteId/daybook'
    | '/sites/$siteId/receipts'
    | '/sites/$siteId/shares'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/daybook'
    | '/more'
    | '/owed'
    | '/people'
    | '/receipts'
    | '/reports'
    | '/more/how-it-looks'
    | '/more/what-for'
    | '/more/which-account'
    | '/more/who-can-sign-in'
    | '/people/$personId'
    | '/receipts/new'
    | '/sites/new'
    | '/more/'
    | '/sites/$siteId/daybook'
    | '/sites/$siteId/receipts'
    | '/sites/$siteId/shares'
    | '/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DaybookRoute: typeof DaybookRoute
  MoreRoute: typeof MoreRouteWithChildren
  OwedRoute: typeof OwedRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  ReceiptsRoute: typeof ReceiptsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SitesNewRoute: typeof SitesNewRoute
  SitesSiteIdDaybookRoute: typeof SitesSiteIdDaybookRoute
  SitesSiteIdReceiptsRoute: typeof SitesSiteIdReceiptsRoute
  SitesSiteIdSharesRoute: typeof SitesSiteIdSharesRoute
  SitesSiteIdIndexRoute: typeof SitesSiteIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owed': {
      id: '/owed'
      path: '/owed'
      fullPath: '/owed'
      preLoaderRoute: typeof OwedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daybook': {
      id: '/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof DaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/': {
      id: '/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof MoreIndexRouteImport
      parentRoute: typeof MoreRoute
    }
    '/sites/new': {
      id: '/sites/new'
      path: '/sites/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof SitesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/new': {
      id: '/receipts/new'
      path: '/new'
      fullPath: '/receipts/new'
      preLoaderRoute: typeof ReceiptsNewRouteImport
      parentRoute: typeof ReceiptsRoute
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/more/who-can-sign-in': {
      id: '/more/who-can-sign-in'
      path: '/who-can-sign-in'
      fullPath: '/more/who-can-sign-in'
      preLoaderRoute: typeof MoreWhoCanSignInRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/which-account': {
      id: '/more/which-account'
      path: '/which-account'
      fullPath: '/more/which-account'
      preLoaderRoute: typeof MoreWhichAccountRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/what-for': {
      id: '/more/what-for'
      path: '/what-for'
      fullPath: '/more/what-for'
      preLoaderRoute: typeof MoreWhatForRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/how-it-looks': {
      id: '/more/how-it-looks'
      path: '/how-it-looks'
      fullPath: '/more/how-it-looks'
      preLoaderRoute: typeof MoreHowItLooksRouteImport
      parentRoute: typeof MoreRoute
    }
    '/sites/$siteId/': {
      id: '/sites/$siteId/'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof SitesSiteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/shares': {
      id: '/sites/$siteId/shares'
      path: '/sites/$siteId/shares'
      fullPath: '/sites/$siteId/shares'
      preLoaderRoute: typeof SitesSiteIdSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/receipts': {
      id: '/sites/$siteId/receipts'
      path: '/sites/$siteId/receipts'
      fullPath: '/sites/$siteId/receipts'
      preLoaderRoute: typeof SitesSiteIdReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/daybook': {
      id: '/sites/$siteId/daybook'
      path: '/sites/$siteId/daybook'
      fullPath: '/sites/$siteId/daybook'
      preLoaderRoute: typeof SitesSiteIdDaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoreRouteChildren {
  MoreHowItLooksRoute: typeof MoreHowItLooksRoute
  MoreWhatForRoute: typeof MoreWhatForRoute
  MoreWhichAccountRoute: typeof MoreWhichAccountRoute
  MoreWhoCanSignInRoute: typeof MoreWhoCanSignInRoute
  MoreIndexRoute: typeof MoreIndexRoute
}

const MoreRouteChildren: MoreRouteChildren = {
  MoreHowItLooksRoute: MoreHowItLooksRoute,
  MoreWhatForRoute: MoreWhatForRoute,
  MoreWhichAccountRoute: MoreWhichAccountRoute,
  MoreWhoCanSignInRoute: MoreWhoCanSignInRoute,
  MoreIndexRoute: MoreIndexRoute,
}

const MoreRouteWithChildren = MoreRoute._addFileChildren(MoreRouteChildren)

interface PeopleRouteChildren {
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeoplePersonIdRoute: PeoplePersonIdRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface ReceiptsRouteChildren {
  ReceiptsNewRoute: typeof ReceiptsNewRoute
}

const ReceiptsRouteChildren: ReceiptsRouteChildren = {
  ReceiptsNewRoute: ReceiptsNewRoute,
}

const ReceiptsRouteWithChildren = ReceiptsRoute._addFileChildren(
  ReceiptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DaybookRoute: DaybookRoute,
  MoreRoute: MoreRouteWithChildren,
  OwedRoute: OwedRoute,
  PeopleRoute: PeopleRouteWithChildren,
  ReceiptsRoute: ReceiptsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SitesNewRoute: SitesNewRoute,
  SitesSiteIdDaybookRoute: SitesSiteIdDaybookRoute,
  SitesSiteIdReceiptsRoute: SitesSiteIdReceiptsRoute,
  SitesSiteIdSharesRoute: SitesSiteIdSharesRoute,
  SitesSiteIdIndexRoute: SitesSiteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
