/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesNewRouteImport } from './routes/sites.new'
import { Route as SitesSiteIdDayRouteImport } from './routes/sites.$siteId.day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesNewRoute = SitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdDayRoute = SitesSiteIdDayRouteImport.update({
  id: '/sites/$siteId/day',
  path: '/sites/$siteId/day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sites/new': typeof SitesNewRoute
  '/sites/$siteId/day': typeof SitesSiteIdDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sites/new': typeof SitesNewRoute
  '/sites/$siteId/day': typeof SitesSiteIdDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sites/new': typeof SitesNewRoute
  '/sites/$siteId/day': typeof SitesSiteIdDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sites/new' | '/sites/$siteId/day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sites/new' | '/sites/$siteId/day'
  id: '__root__' | '/' | '/sites/new' | '/sites/$siteId/day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitesNewRoute: typeof SitesNewRoute
  SitesSiteIdDayRoute: typeof SitesSiteIdDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/new': {
      id: '/sites/new'
      path: '/sites/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof SitesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/day': {
      id: '/sites/$siteId/day'
      path: '/sites/$siteId/day'
      fullPath: '/sites/$siteId/day'
      preLoaderRoute: typeof SitesSiteIdDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitesNewRoute: SitesNewRoute,
  SitesSiteIdDayRoute: SitesSiteIdDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
