// Ten years of workbooks accumulated 66 header labels for roughly 45 real trades; this is the merged list.

// False only for money not spent building. Building cost is the sum over the true ones, which replaces subtracting the plot column back out by hand.
export const CANONICAL_TRADES: Array<{ name: string; countsAsBuildingCost: boolean }> = [
  { name: 'Civil labour', countsAsBuildingCost: true },
  { name: 'Bricks', countsAsBuildingCost: true },
  { name: 'Cement', countsAsBuildingCost: true },
  { name: 'Crush', countsAsBuildingCost: true },
  { name: 'Sand', countsAsBuildingCost: true },
  { name: 'Steel', countsAsBuildingCost: true },
  { name: 'Earth filling', countsAsBuildingCost: true },
  { name: 'Tile fixing', countsAsBuildingCost: true },
  { name: 'Ceramic tiles', countsAsBuildingCost: true },
  { name: 'Granite and marble', countsAsBuildingCost: true },
  { name: 'Garage and wall tiles', countsAsBuildingCost: true },
  { name: 'Electrical labour', countsAsBuildingCost: true },
  { name: 'Electrical items', countsAsBuildingCost: true },
  { name: 'Air conditioning', countsAsBuildingCost: true },
  { name: 'Plumbing labour', countsAsBuildingCost: true },
  { name: 'Sanitary fittings', countsAsBuildingCost: true },
  { name: 'Sanitary pipework', countsAsBuildingCost: true },
  { name: 'Kitchens and wardrobes', countsAsBuildingCost: true },
  { name: 'Doors', countsAsBuildingCost: true },
  { name: 'Carpentry labour', countsAsBuildingCost: true },
  { name: 'Wood and hardware', countsAsBuildingCost: true },
  { name: 'Steel fabrication', countsAsBuildingCost: true },
  { name: 'Aluminium work', countsAsBuildingCost: true },
  { name: 'Glass', countsAsBuildingCost: true },
  { name: 'Painting', countsAsBuildingCost: true },
  { name: 'Texture paint', countsAsBuildingCost: true },
  { name: 'False ceiling', countsAsBuildingCost: true },
  // An exterior wall finish of cement, plaster of Paris and bondo. Its own trade, not painting and not plastering.
  { name: 'Graphy', countsAsBuildingCost: true },
  // A mouldable waterproof solid surface for counter tops. A material, not a person, despite reading as one in the workbooks.
  { name: 'Corian', countsAsBuildingCost: true },
  { name: 'Fibre relief and mosaic', countsAsBuildingCost: true },
  { name: 'Wall paper and blinds', countsAsBuildingCost: true },
  { name: 'Wooden flooring', countsAsBuildingCost: true },
  { name: 'Appliances', countsAsBuildingCost: true },
  { name: 'Smoke detectors and cameras', countsAsBuildingCost: true },
  { name: 'Furnishing', countsAsBuildingCost: true },
  { name: 'Swimming pool', countsAsBuildingCost: true },
  { name: 'Landscaping', countsAsBuildingCost: true },
  { name: 'Gas connection', countsAsBuildingCost: true },
  { name: 'Watchman salary', countsAsBuildingCost: true },
  { name: 'Labour', countsAsBuildingCost: true },
  { name: 'Architect fee', countsAsBuildingCost: true },
  // A cost to the site and income to whoever supervises it, from one payment entered once.
  { name: 'Supervision charges', countsAsBuildingCost: true },
  { name: 'Utility bills and authority charges', countsAsBuildingCost: true },
  // The workbooks needed a bucket, and forcing a choice makes people file things in the wrong place.
  { name: 'Other', countsAsBuildingCost: true },
  { name: 'Plot, taxes and commission', countsAsBuildingCost: false },
]
